image:
  repository: docker.ssc-hn.com/bigdata/ssc-hadoop
  tag: v3.3.6
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 3.3.6
logLevel: INFO

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

hdfs:
  nameNode:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
    zookeeperQuorum: "zookeeper-0.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.default.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.default.svc.cluster.local:2181"


  dataNode:
    # Will be used as dfs.datanode.hostname
    # You still need to set up services + ingress for every DN
    # Datanodes will expect to
    externalHostname: ssc-hn-hadoop.com
    externalDataPortRangeStart: 50500
    externalHTTPPortRangeStart: 51000
    replicas: 3
    pdbMinAvailable: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  webhdfs:
    enabled: true

  jounralNode:
    replicas: 3
    pdbMinAvailable: 2
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

persistence:
  nameNode:
    enabled: true
    storageClass: "directpv-min-io"
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: true
    storageClass: "directpv-min-io"
    accessMode: ReadWriteOnce
    size: 200Gi

  journalNode:
    enabled: true
    storageClass: "directpv-min-io"
    accessMode: ReadWriteOnce
    size: 100Gi
