logLevel: INFO

antiAffinity: "soft"  # 最简单部署，不考虑强分布

hdfs:
  clusterName: "min-hadoop"

  rpcAddress: "min-hadoop-hdfs-nn-0:9000"  # ➤ 关键：用于 core-site.xml fs.defaultFS 多NN模式

  nameNode:
    replicas: 3  # 修改为3个namenode
    resources:
      requests:
        memory: "512Mi"
        cpu: "50m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    zookeeperQuorum: ""  # 不使用 zk，禁用 HA

  dataNode:
    replicas: 3  # 修改为3个datanode
    resources:
      requests:
        memory: "512Mi"
        cpu: "50m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  replication: 3  # 修改复制因子为3
  webhdfs:
    enabled: false

  journalNode:
    replicas: 0  # 完全禁用 JN

persistence:
  nameNode:
    enabled: true  # 启用namenode持久化
    size: "10Gi"
    accessMode: "ReadWriteOnce"
    storageClass: ""  # 使用默认存储类

  dataNode:
    enabled: true  # 启用datanode持久化
    size: "20Gi"
    accessMode: "ReadWriteOnce"
    storageClass: ""  # 使用默认存储类

  journalNode:
    enabled: false

image:
  repository: hadoop-xxt
  tag: "3.3.6"
  pullPolicy: IfNotPresent

