apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hadoop.fullname" . }}-journalnode
  labels:
    app.kubernetes.io/component: journalnode
spec:
  serviceName: {{ include "hadoop.fullname" . }}-journalnode
  replicas: 3  # 至少3个副本
  selector:
    matchLabels:
      app.kubernetes.io/component: journalnode
  template:
    metadata:
      labels:
        app.kubernetes.io/component: journalnode
    spec:
      # 设置 Pod 反亲和性，确保 JournalNode Pod 分布在不同的节点上
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: journalnode
      containers:
        - name: journalnode
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - "/bin/bash"
            - "/tmp/hadoop-config/bootstrap.sh"
            - "-journalnode"  # 新增启动参数
          volumeMounts:
            - name: hadoop-config
              mountPath: /tmp/hadoop-config
            - name: journaldata
              mountPath: /root/hdfs/journalnode
   {{- if .Values.persistence.journalNode.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: journaldata  # 修正为与 volumeMounts 中的名称匹配
        labels:
          app.kubernetes.io/name: {{ include "hadoop.name" . }}
          helm.sh/chart: {{ include "hadoop.chart" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: journalnode  # 修正为 journalnode
      spec:
        accessModes:
          - {{ .Values.persistence.journalNode.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.journalNode.size | quote }}
            # 根据配置设置存储类
        {{- if .Values.persistence.journalNode.storageClass }}
          {{- if (eq "-" .Values.persistence.journalNode.storageClass) }}
            storageClassName: ""
          {{- else }}
            storageClassName: "{{ .Values.persistence.journalNode.storageClass }}"
          {{- end }}
        {{- else }}
          # 如果未配置存储类，使用 emptyDir
          - name: journaldata
            emptyDir: {}
        {{- end }}
       {{- end }}